## Implimating ACP using R

Importing the dataSet

```{r}
# Install required packages if not already installed
install.packages("FactoMineR")
install.packages("factoextra")
```

```{r}
data<-read.csv('./Data/decathlon.csv')
```

```{r}
str(data)
```

```{r}
# Select numeric columns
numeric_data <- data[sapply(data, is.numeric)]
```

```{r}
numeric_data
```

```{r}
# Standardize the data
scaled_data <- scale(numeric_data)

```

```{r}
# Perform PCA
library(FactoMineR)
library(factoextra)
pca_result <- PCA(scaled_data, graph = TRUE)
```

```{r}
pca_result$eig
```

```{r}
library(factoextra)
fviz_eig(pca_result)
```

```{r}
pca_result$ind$coord
```

```{r}
nrow(data)
```

```{r}
pca_result$var$coord
```

```{r}
# Qualité de représentation des individus (cos²)
 pca_result$ind$cos2*100
```

```{r}
# Qualité de représentation des variables (cos²)
 variable_quality=pca_result$var$cos2*100
 
```

```{r}
variable_quality

```

```{r}
# Créer les nouvelles colonnes
variable_quality <- as.data.frame(variable_quality)
variable_quality$`Dim.1_Dim.2` <- variable_quality$Dim.1 + variable_quality$Dim.2
variable_quality$`Dim.1_Dim.3` <- variable_quality$Dim.1 + variable_quality$Dim.3


variable_quality
```

```{r}
variable_quality[, ncol(variable_quality)-1:ncol(variable_quality)]
variable_quality[, (ncol(variable_quality)-1):ncol(variable_quality)]

```

```{r}
# Calculating the sum of each column in the dataframe
column_sums <- colSums(variable_quality[, (ncol(variable_quality)-1):ncol(variable_quality)])

# Display the result
print(column_sums)

```

```{r}
# Visualisation des individus (plan factoriel)
fviz_pca_ind(pca_result,
             col.ind = "cos2", # Colorer selon la qualité de représentation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE)    # Éviter les chevauchements des étiquettes

```

```{r}
# Visualisation des variables (cercle des corrélations)
fviz_pca_var(pca_result,
             col.var = "contrib", # Colorer selon la contribution
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)       # Éviter les chevauchements des étiquettes

```

```{r}
# Visualisation biplot (individus + variables)
fviz_pca_biplot(pca_result,
                repel = TRUE,        # Éviter les chevauchements
                col.var = "#2E9FDF", # Couleur des variables
                col.ind = "#696969") # Couleur des individus
```
